name: taskcluster
appVersion: '84.1.0'
description:  Framework that supports Mozilla's continuous integration and release processes.
version: 0.3.2
keywords:
  - ci
  - ci-framework
sources:
  - https://github.com/taskcluster/taskcluster
icon: https://media.taskcluster.net/logo/logo.png
