name: taskcluster
appVersion: '68.0.4'
description:  Framework that supports Mozilla's continuous integration and release processes.
version: 0.2.1
keywords:
  - ci
  - ci-framework
sources:
  - https://github.com/taskcluster/taskcluster
icon: https://media.taskcluster.net/logo/logo.png
