---
trust-domain: taskcluster
# this is lower priority than the decision task
task-priority: high

taskgraph:
  register: src:register
  repositories:
    taskcluster:
      name: taskcluster

workers:
  aliases:
    release:
      provisioner: proj-taskcluster
      os: linux
      implementation: generic-worker
      worker-type: release
    gw-ubuntu-24-04:
      provisioner: proj-taskcluster
      os: linux
      implementation: generic-worker
      worker-type: gw-ubuntu-24-04
    ubuntu-24-04:
      provisioner: proj-taskcluster
      os: linux
      implementation: docker-worker
      worker-type: gw-ubuntu-24-04
    gw-ubuntu-24-04-gui:
      provisioner: proj-taskcluster
      os: linux
      implementation: generic-worker
      worker-type: gw-ubuntu-24-04-gui
    gw-ci-macos:
      provisioner: proj-taskcluster
      os: macosx
      implementation: generic-worker
      worker-type: gw-ci-macos
    gw-windows-2022:
      provisioner: proj-taskcluster
      os: windows
      implementation: generic-worker
      worker-type: gw-windows-2022
    gw-windows-2022-gui:
      provisioner: proj-taskcluster
      os: windows
      implementation: generic-worker
      worker-type: gw-windows-2022-gui
    images:
      provisioner: proj-taskcluster
      os: linux
      implementation: docker-worker
      worker-type: gw-ubuntu-24-04
