defaults:
  # Taskcluster credentials
  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env:secret TASKCLUSTER_ACCESS_TOKEN

  monitoring:
    level: !env:optional LEVEL
    errorConfig: !env:json:secret:optional ERROR_CONFIG

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:secret:optional NEW_RELIC
