{{- if not (has "secret" .Values.skipResourceTypes) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-github
  labels:
    app.kubernetes.io/name: taskcluster-github
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-github-secrets
    app.kubernetes.io/part-of: taskcluster
data:
  TASKCLUSTER_ACCESS_TOKEN: '{{ if typeIs "<nil>" .Values.github.taskcluster_access_token }}{{ else }}{{ if typeIs "string" .Values.github.taskcluster_access_token }}{{ .Values.github.taskcluster_access_token | b64enc }}{{ else }}{{ .Values.github.taskcluster_access_token | toJson | b64enc }}{{ end }}{{ end }}'
  GITHUB_PRIVATE_PEM: '{{ if typeIs "<nil>" .Values.github.github_private_pem }}{{ else }}{{ if typeIs "string" .Values.github.github_private_pem }}{{ .Values.github.github_private_pem | b64enc }}{{ else }}{{ .Values.github.github_private_pem | toJson | b64enc }}{{ end }}{{ end }}'
  WEBHOOK_SECRET: '{{ if typeIs "<nil>" .Values.github.webhook_secret }}{{ else }}{{ if typeIs "string" .Values.github.webhook_secret }}{{ .Values.github.webhook_secret | b64enc }}{{ else }}{{ .Values.github.webhook_secret | toJson | b64enc }}{{ end }}{{ end }}'
  READ_DB_URL: '{{ if typeIs "<nil>" .Values.github.read_db_url }}{{ else }}{{ if typeIs "string" .Values.github.read_db_url }}{{ .Values.github.read_db_url | b64enc }}{{ else }}{{ .Values.github.read_db_url | toJson | b64enc }}{{ end }}{{ end }}'
  WRITE_DB_URL: '{{ if typeIs "<nil>" .Values.github.write_db_url }}{{ else }}{{ if typeIs "string" .Values.github.write_db_url }}{{ .Values.github.write_db_url | b64enc }}{{ else }}{{ .Values.github.write_db_url | toJson | b64enc }}{{ end }}{{ end }}'
  ERROR_CONFIG: '{{ if typeIs "<nil>" .Values.errorConfig }}{{ else }}{{ if typeIs "string" .Values.errorConfig }}{{ .Values.errorConfig | b64enc }}{{ else }}{{ .Values.errorConfig | toJson | b64enc }}{{ end }}{{ end }}'
  PULSE_USERNAME: '{{ if typeIs "<nil>" .Values.github.pulse_username }}{{ else }}{{ if typeIs "string" .Values.github.pulse_username }}{{ .Values.github.pulse_username | b64enc }}{{ else }}{{ .Values.github.pulse_username | toJson | b64enc }}{{ end }}{{ end }}'
  PULSE_PASSWORD: '{{ if typeIs "<nil>" .Values.github.pulse_password }}{{ else }}{{ if typeIs "string" .Values.github.pulse_password }}{{ .Values.github.pulse_password | b64enc }}{{ else }}{{ .Values.github.pulse_password | toJson | b64enc }}{{ end }}{{ end }}'
  NEW_RELIC: '{{ if typeIs "<nil>" .Values.newRelic }}{{ else }}{{ if typeIs "string" .Values.newRelic }}{{ .Values.newRelic | b64enc }}{{ else }}{{ .Values.newRelic | toJson | b64enc }}{{ end }}{{ end }}'
{{- end }}
