{{- if not (has "secret" .Values.skipResourceTypes) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-index
  labels:
    app.kubernetes.io/name: taskcluster-index
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-index-secrets
    app.kubernetes.io/part-of: taskcluster
data:
  READ_DB_URL: '{{ if typeIs "<nil>" .Values.index.read_db_url }}{{ else }}{{ if typeIs "string" .Values.index.read_db_url }}{{ .Values.index.read_db_url | b64enc }}{{ else }}{{ .Values.index.read_db_url | toJson | b64enc }}{{ end }}{{ end }}'
  WRITE_DB_URL: '{{ if typeIs "<nil>" .Values.index.write_db_url }}{{ else }}{{ if typeIs "string" .Values.index.write_db_url }}{{ .Values.index.write_db_url | b64enc }}{{ else }}{{ .Values.index.write_db_url | toJson | b64enc }}{{ end }}{{ end }}'
  ERROR_CONFIG: '{{ if typeIs "<nil>" .Values.errorConfig }}{{ else }}{{ if typeIs "string" .Values.errorConfig }}{{ .Values.errorConfig | b64enc }}{{ else }}{{ .Values.errorConfig | toJson | b64enc }}{{ end }}{{ end }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ if typeIs "<nil>" .Values.index.taskcluster_access_token }}{{ else }}{{ if typeIs "string" .Values.index.taskcluster_access_token }}{{ .Values.index.taskcluster_access_token | b64enc }}{{ else }}{{ .Values.index.taskcluster_access_token | toJson | b64enc }}{{ end }}{{ end }}'
  PULSE_USERNAME: '{{ if typeIs "<nil>" .Values.index.pulse_username }}{{ else }}{{ if typeIs "string" .Values.index.pulse_username }}{{ .Values.index.pulse_username | b64enc }}{{ else }}{{ .Values.index.pulse_username | toJson | b64enc }}{{ end }}{{ end }}'
  PULSE_PASSWORD: '{{ if typeIs "<nil>" .Values.index.pulse_password }}{{ else }}{{ if typeIs "string" .Values.index.pulse_password }}{{ .Values.index.pulse_password | b64enc }}{{ else }}{{ .Values.index.pulse_password | toJson | b64enc }}{{ end }}{{ end }}'
  NEW_RELIC: '{{ if typeIs "<nil>" .Values.newRelic }}{{ else }}{{ if typeIs "string" .Values.newRelic }}{{ .Values.newRelic | b64enc }}{{ else }}{{ .Values.newRelic | toJson | b64enc }}{{ end }}{{ end }}'
{{- end }}
