{{- if not (has "secret" .Values.skipResourceTypes) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-queue
  labels:
    app.kubernetes.io/name: taskcluster-queue
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-queue-secrets
    app.kubernetes.io/part-of: taskcluster
data:
  TASKCLUSTER_ACCESS_TOKEN: '{{ if typeIs "<nil>" .Values.queue.taskcluster_access_token }}{{ else }}{{ if typeIs "string" .Values.queue.taskcluster_access_token }}{{ .Values.queue.taskcluster_access_token | b64enc }}{{ else }}{{ .Values.queue.taskcluster_access_token | toJson | b64enc }}{{ end }}{{ end }}'
  ERROR_CONFIG: '{{ if typeIs "<nil>" .Values.errorConfig }}{{ else }}{{ if typeIs "string" .Values.errorConfig }}{{ .Values.errorConfig | b64enc }}{{ else }}{{ .Values.errorConfig | toJson | b64enc }}{{ end }}{{ end }}'
  READ_DB_URL: '{{ if typeIs "<nil>" .Values.queue.read_db_url }}{{ else }}{{ if typeIs "string" .Values.queue.read_db_url }}{{ .Values.queue.read_db_url | b64enc }}{{ else }}{{ .Values.queue.read_db_url | toJson | b64enc }}{{ end }}{{ end }}'
  WRITE_DB_URL: '{{ if typeIs "<nil>" .Values.queue.write_db_url }}{{ else }}{{ if typeIs "string" .Values.queue.write_db_url }}{{ .Values.queue.write_db_url | b64enc }}{{ else }}{{ .Values.queue.write_db_url | toJson | b64enc }}{{ end }}{{ end }}'
  PULSE_USERNAME: '{{ if typeIs "<nil>" .Values.queue.pulse_username }}{{ else }}{{ if typeIs "string" .Values.queue.pulse_username }}{{ .Values.queue.pulse_username | b64enc }}{{ else }}{{ .Values.queue.pulse_username | toJson | b64enc }}{{ end }}{{ end }}'
  PULSE_PASSWORD: '{{ if typeIs "<nil>" .Values.queue.pulse_password }}{{ else }}{{ if typeIs "string" .Values.queue.pulse_password }}{{ .Values.queue.pulse_password | b64enc }}{{ else }}{{ .Values.queue.pulse_password | toJson | b64enc }}{{ end }}{{ end }}'
  AWS_ACCESS_KEY_ID: '{{ if typeIs "<nil>" .Values.queue.aws_access_key_id }}{{ else }}{{ if typeIs "string" .Values.queue.aws_access_key_id }}{{ .Values.queue.aws_access_key_id | b64enc }}{{ else }}{{ .Values.queue.aws_access_key_id | toJson | b64enc }}{{ end }}{{ end }}'
  AWS_SECRET_ACCESS_KEY: '{{ if typeIs "<nil>" .Values.queue.aws_secret_access_key }}{{ else }}{{ if typeIs "string" .Values.queue.aws_secret_access_key }}{{ .Values.queue.aws_secret_access_key | b64enc }}{{ else }}{{ .Values.queue.aws_secret_access_key | toJson | b64enc }}{{ end }}{{ end }}'
  NEW_RELIC: '{{ if typeIs "<nil>" .Values.newRelic }}{{ else }}{{ if typeIs "string" .Values.newRelic }}{{ .Values.newRelic | b64enc }}{{ else }}{{ .Values.newRelic | toJson | b64enc }}{{ end }}{{ end }}'
{{- end }}
